name: test_render_bloc
description: A new Flutter project.
environment:
  sdk: ">=2.15.1 <3.0.0"
dependencies:
  bloc: ^8.0.2
  flutter:
    sdk: flutter
  flutter_bloc: ^8.0.1
  flutter_localizations:
    sdk: flutter
  flutter_services_binding: ^0.1.0
  intl: ^0.17.0
  equatable: ^2.0.3

dev_dependencies:
  bloc_test: ^9.0.2
  flutter_test:
    sdk: flutter
  mockingjay: ^0.2.0
  mocktail: ^0.2.0
flutter:
  uses-material-design: true
  generate: true